### PR TITLE
[CORE] Fix jetty vulnerabilities.

### PR DESCRIPTION
**Pull request by zhangbinzaifendou**
**What changes were proposed in this pull request?**
```
1. The current code uses org.eclipse.jetty:jetty-server:9.3.24.v20180605 and it will cause a security vulnerabilities.
 We received some alerts like https://github.com/Qihoo360/XSQL/network/alert/pom.xml/org.eclipse.jetty:jetty-server/open
This Alert remind to upgrate the version of jetty-server to 9.4.18.v20190429 or later.
The jetty version used in spark3.0 is 9.4.18.v20190429.
2. when chanage the version of jetty-server to  9.4.18.v20190429 the ExecutorThreadPool(ExecutorService) 
constructor can't be found
```

### CODE REVIEW

**Comment by beliefer** [comment]
Do you reference the version of jetty in `Apache Spark` ?

**Comment by zhangbinzaifendou** [comment]
The jetty version used in spark3.0 is 9.4.18.v20190429 and 9.4.x has incompatibility issues.

**Comment by beliefer** [comment]
I think we should wait to upgrade `Spark 3.0.0` and avoid unnecessary code coupling.

**Comment by beliefer** [comment]
cc @WeiWenda

**Pull request merged**
